export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INIT_INGREDIENTS_START = 'SET_INIT_INGREDIENTS_START';
export const SET_INIT_INGREDIENTS ='SET_INIT_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED ='FETCH_INGREDIENTS_FAILED'; 

export const PURCHASABLE_BURGER_SUCCESS ='PURCHASABLE_BURGER_SUCCESS';
export const PURCHASABLE_BURGER_FAIL ='PURCHASABLE_BURGER_FAIL';
export const PURCHASABLE_BURGER_START ='PURCHASABLE_BURGER_START';
export const PURCHASABLE_BURGER = 'PURCHASABLE_BURGER';

export const FETCH_ORDERS_START ='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS ='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS ='FETCH_ORDERS';
export const AUTH_CHECK_STATE ='AUTH_CHECK_STATE';
export const AUTH_USER ='AUTH_USER';
export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAIL ='AUTH_FAIL';

export const AUTH_CHECK_TIMEOUT ='AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT ='AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT ='AUTH_LOGOUT';
